set(Plugin-Name "CaPTk Interactive Segmentation")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "CBICA")
set(Plugin-ContactAddress "https://www.med.upenn.edu/cbica/")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
