#ifndef CaPTkWriteJsonToFile_h
#define CaPTkWriteJsonToFile_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <json/json.h>

#include <string>

namespace captk
{
/**\brief Write Json::Value object to file */
MITKCAPTKCOMMON_EXPORT void WriteJsonToFile(Json::Value json, std::string outputfile);
}

#endif // ! #ifndef CaPTkWriteJsonToFile_h