#ifndef CaPTkCohort_h
#define CaPTkCohort_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

namespace captk
{
class CohortSubject;
}

#include <QObject>
#include <QString>
#include <QList>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT Cohort : public QObject
{
    Q_OBJECT

public:
    explicit Cohort(QObject* parent = nullptr);

    ~Cohort();

    void LoadFromJson(QString jsonPath);

    /* Getters */

    QString GetName();

    QList<CohortSubject*> GetSubjects();

    /* Setters */

    void SetName(QString name);

    void SetSubjects(QList<CohortSubject*> subjects);

private:
    QString m_Name;
    QList<CohortSubject*> m_Subjects;
};
}

#endif // ! CaPTkCohort_h