#ifndef CaPTkCohortImage_h
#define CaPTkCohortImage_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <QObject>
#include <QString>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT CohortImage : public QObject
{
    Q_OBJECT

public:
    explicit CohortImage(QObject* parent = nullptr);

    ~CohortImage();

    /* Getters */

    QString GetPath();

    QString GetImageInfoPath();

    /* Setters */

    void SetPath(QString path);

    void SetImageInfoPath(QString imageInfoPath);

private:
    QString m_Path;
    QString m_ImageInfoPath;
};
}

#endif // ! CaPTkCohortImage_h