#ifndef CaPTkCohortSubject_h
#define CaPTkCohortSubject_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

namespace captk
{
class CohortStudy;
}

#include <QObject>
#include <QString>
#include <QList>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT CohortSubject : public QObject
{
    Q_OBJECT

public:
    explicit CohortSubject(QObject* parent = nullptr);

    ~CohortSubject();

    /* Getters */

    QString GetName();

    QList<captk::CohortStudy*> GetStudies();

    /* Setters */

    void SetName(QString name);

    void SetStudies(QList<captk::CohortStudy*> studies);

private:
    QString m_Name;
    QList<captk::CohortStudy*> m_Studies;
};
}

#endif // ! CaPTkCohortSubject_h