#ifndef CaPTkCohortStudy_h
#define CaPTkCohortStudy_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

namespace captk
{
class CohortSeries;
}

#include <QObject>
#include <QString>
#include <QList>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT CohortStudy : public QObject
{
    Q_OBJECT

public:
    explicit CohortStudy(QObject* parent = nullptr);

    ~CohortStudy();

    /* Getters */

    QString GetName();

    QList<captk::CohortSeries*> GetSeries();

    /* Setters */

    void SetName(QString name);

    void SetSeries(QList<captk::CohortSeries*> series);

private:
    QString m_Name;
    QList<captk::CohortSeries*> m_Series;
};
}

#endif // ! CaPTkCohortStudy_h