#ifndef CaPTkCohortImage_h
#define CaPTkCohortImage_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <QString>

namespace captk
{
/** \class CohortImage
 * \brief Defines information about an image
 */
class MITKCAPTKCOMMON_EXPORT CohortImage
{
public:
    CohortImage();

    ~CohortImage();

    /* Getters */

    QString GetPath();

    /** \brief Get the path to the (optional) image information file
     * 
     * Image info is reserved for a file that holds meta-data about an image
     * \return the image info path. Empty QString if there is no such file
     */
    QString GetImageInfoPath();

    /* Setters */

    void SetPath(QString path);

    /** \brief Set the path to the (optional) image information file
     * 
     * Image info is reserved for a file that holds meta-data about an image
     */
    void SetImageInfoPath(QString imageInfoPath);

private:
    QString m_Path;
    QString m_ImageInfoPath;
};
}

#endif // ! CaPTkCohortImage_h