#ifndef CaPTkCohortStudy_h
#define CaPTkCohortStudy_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

namespace captk
{
class CohortSeries;
}

#include <QString>
#include <QList>
#include <QSharedPointer>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT CohortStudy
{
/** \class CohortStudy
 * \brief Defines information about a study
 * and holds the study various list of "series".
 * 
 * Note: series is a combination of modality and 
 * acquisition protocol. Multiple series can happen
 * in a study.
 */
public:
    CohortStudy();

    ~CohortStudy();

    /* Getters */

    QString GetName();

    QList<QSharedPointer<CohortSeries>> GetSeries();

    /* Setters */

    void SetName(QString name);

    void SetSeries(QList<QSharedPointer<CohortSeries>> series);

private:
    QString m_Name;
    QList<QSharedPointer<CohortSeries>> m_Series;
};
}

#endif // ! CaPTkCohortStudy_h