#ifndef CaPTkCohortJsonFromFilesystem_h
#define CaPTkCohortJsonFromFilesystem_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <QString>
#include <QStringList>
#include <QList>
#include <QSharedPointer>
#include <QJsonDocument>

#include <string>
#include <vector>

namespace captk
{

/** \brief Merge two json cohorts into one
 *
 * Each subject that appears on both will have it's images concatenated
 */
MITKCAPTKCOMMON_EXPORT QSharedPointer<QJsonDocument> 
CohortJsonMergeObjects(QList<QSharedPointer<QJsonDocument>> jsons);

/** \brief Get a QJsonDocument containing the information of a cohort from file */
MITKCAPTKCOMMON_EXPORT QSharedPointer<QJsonDocument> 
CohortJsonFromDirectoryStructure(QString& directory);

/** \namespace internal Contains helper functions for cohort json processing */
namespace internal
{	
	MITKCAPTKCOMMON_EXPORT QStringList GetSubdirectories(QString& directory);
	MITKCAPTKCOMMON_EXPORT QStringList GetContainedFiles(QString& directory); /// of a dir

	MITKCAPTKCOMMON_EXPORT QString GetFileNameFromPath(QString& path);
	MITKCAPTKCOMMON_EXPORT bool IsDir(QString& path);
}

}

#endif // ! #ifndef CaPTkCohortJsonFromFilesystem_h