#ifndef CaPTkROIConstructionHelperBase_h
#define CaPTkROIConstructionHelperBase_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <mitkLabelSetImage.h>

#include <string>
#include <vector>

namespace captk
{
/** \class ROIConstructionHelperBase
 * \brief Non-templated class to serve as base class for ROIConstructionHelper
 */
class MITKCAPTKCOMMON_EXPORT ROIConstructionHelperBase
{
public:
    ROIConstructionHelperBase() {}

    virtual ~ROIConstructionHelperBase() {}

    enum MODE
    {
        ROI_BASED,
        FULL
    }

    virtual void Update(
        float radius,
        float step
    ) = 0;

    virtual bool HasNext() = 0;

    // virtual void SetValuesAndNames(mitk::LabelSet::Pointer labelSet) = 0;

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase &operator++() # suffix
    {
        this->OnIncrement(); // call actual operation function
        return *this;
    }

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase operator++(int) # postfix (calls suffix)
    {
        ROIConstructionHelperBase tmp(*this);
        operator++(); // call suffix
        return tmp;
    }

    void SetMode(MODE mode)
    {
        m_Mode = mode;
    }

    virtual void PopulateMask(mitk::LabelSetImage::Pointer rMask) = 0;

protected:
    virtual void OnIncrement() = 0;

    MODE m_Mode = MODE::ROI_BASED;
};
} // namespace captk

#endif // ! CaPTkROIConstructionHelperBase_h