#ifndef CaPTkROIConstructionHelperBase_h
#define CaPTkROIConstructionHelperBase_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <mitkLabelSetImage.h>

#include <string>
#include <vector>

namespace captk
{
/** \class ROIConstructionHelperBase
 * \brief Non-templated class to serve as base class for ROIConstructionHelper
 */
class MITKCAPTKCOMMON_EXPORT ROIConstructionHelperBase
{
public:
    ROIConstructionHelperBase();

    virtual ~ROIConstructionHelperBase();

    virtual void Update(
        float radius,
        float step
    );

    virtual void GoToBegin();

    virtual bool IsAtEnd();

    virtual void SetValuesAndNames(
        std::vector<int>         values,
        std::vector<std::string> names
    );

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase& operator++(); // prefix

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase operator++(int); // suffix (calls prefix)

    virtual float PopulateMask(mitk::LabelSetImage::Pointer rMask);

protected:
    virtual void OnIncrement();

};
} // namespace captk

#endif // ! CaPTkROIConstructionHelperBase_h
