#ifndef CaPTkROIConstructionHelperBase_h
#define CaPTkROIConstructionHelperBase_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <mitkLabelSetImage.h>

#include <string>
#include <vector>

namespace captk
{
/** \class ROIConstructionHelperBase
 * \brief Non-templated class to serve as base class for ROIConstructionHelper
 */
class MITKCAPTKCOMMON_EXPORT ROIConstructionHelperBase
{
public:
    ROIConstructionHelperBase() {}

    virtual ~ROIConstructionHelperBase() {}

    virtual void Update(
        float /*radius*/,
        float /*step*/)
    {
        // Cannot have pure virtual because we want to use the base class
    }

    virtual void GoToBegin()
    {

    }

    virtual bool IsAtEnd()
    {
        return true; // Return is required and we don't want this to be pure virtual
    }

    virtual void SetValuesAndNames(
        std::vector<int>         /*values*/,
        std::vector<std::string> /*names*/)
    {
        
    }

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase &operator++() // prefix
    {
        this->OnIncrement(); // call actual operation function
        return *this;
    }

    /** \brief ++ overloading to go to the next lattice */
    ROIConstructionHelperBase operator++(int) // postfix (calls suffix)
    {
        ROIConstructionHelperBase tmp(*this);
        ++*this; // call suffix
        return tmp;
    }

    virtual float PopulateMask(mitk::LabelSetImage::Pointer /*rMask*/)
    {
        return 0.0f; // Return is required and we don't want this to be pure virtual
    }

protected:
    virtual void OnIncrement()
    {

    }
};
} // namespace captk

#endif // ! CaPTkROIConstructionHelperBase_h