#ifndef CaPTkROIConstructionItkHelperBase_h
#define CaPTkROIConstructionItkHelperBase_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCaPTkCommonExports.h>

#include <mitkLabelSetImage.h>

#include <string>
#include <vector>

namespace captk
{
class MITKCAPTKCOMMON_EXPORT ROIConstructionItkHelperBase
{
public:

    ROIConstructionItkHelperBase() {}

    virtual ~ROIConstructionItkHelperBase() {}

    virtual void SetValuesAndNames(
        std::vector<int> values, 
        std::vector<std::string> names) = 0;

    virtual size_t GetPropertiesSize() = 0;

    virtual void Update(
        bool  lattice,
        float window,
        bool  fluxNeumannCondition,
        bool  patchConstructionROI,
        bool  patchConstructionNone,
        float step
    ) = 0;

    virtual std::string GetPropertyLabel(size_t patchPos) = 0;

    virtual int GetPropertyValue(size_t patchPos) = 0;

    virtual void PopulateMaskAtPatch(
        size_t patchPos, 
        mitk::LabelSetImage::Pointer miniMask) = 0;
};
}

#endif // ! CaPTkROIConstructionItkHelperBase_h