set(Plugin-Name "CaPTk PHI Estimator Plugin")
set(Plugin-Version "1.0")
set(Plugin-Vendor "CBICA")
set(Plugin-ContactAddress "https://www.med.upenn.cbica/")
set(Require-Plugin org.mitk.gui.qt.common)
